import { ScaleBaseType } from '@type/timeline';

export const timeLineScales: ScaleBaseType[] = [
  { // 0
    index: 0,
    maxFrame: 50,
    minFrame: 100/3,
    largeCell: 2,
    cellNums: 2,
    unit: 'frame',
  },
  { // 1
    index: 1,
    maxFrame: 100/3,
    minFrame: 20,
    largeCell: 3,
    cellNums: 3,
    unit: 'frame',
  },
  { // 2
    index: 2,
    maxFrame: 20,
    minFrame: 10,
    largeCell: 5,
    cellNums: 5,
    unit: 'frame',
  },
  { // 3
    index: 3,
    maxFrame: 10,
    minFrame: 20/3,
    largeCell: 10,
    cellNums: 10,
    unit: 'frame',
  },
  { // 4
    index: 4,
    maxFrame: 20/3,
    minFrame: 10/3,
    largeCell: 15,
    cellNums: 3,
    unit: 'frame',
  },
  { // 5
    index: 5,
    maxFrame: 10/3,
    minFrame: 5/3,
    largeCell: 30,
    cellNums: 10,
    unit: 'second',
  },
  { // 6
    index: 6,
    maxFrame: 5/3,
    minFrame: 10/9,
    largeCell: 60,
    cellNums: 10,
    unit: 'second',
  },
  { // 7
    index: 7,
    maxFrame: 10/9,
    minFrame: 2/3,
    largeCell: 90,
    cellNums: 10,
    unit: 'second',
  },
  { // 8
    index: 8,
    maxFrame: 2/3,
    minFrame: 1/3,
    largeCell: 150,
    cellNums: 10,
    unit: 'second',
  },
  { // 9
    index: 9,
    maxFrame: 1/3,
    minFrame: 1/6,
    largeCell: 300,
    cellNums: 10,
    unit: 'second',
  },
  { // 10
    index: 10,
    maxFrame: 1/6,
    minFrame: 1/9,
    largeCell: 600,
    cellNums: 10,
    unit: 'second',
  },
  { // 11
    index: 11,
    maxFrame: 1/9,
    minFrame: 1/12,
    largeCell: 900,
    cellNums: 10,
    unit: 'second',
  },
  { // 12
    index: 12,
    maxFrame: 1/12,
    minFrame: 1/24,
    largeCell: 1200,
    cellNums: 10,
    unit: 'second',
  },
  { // 13
    index: 13,
    maxFrame: 1/24,
    minFrame: 1/48,
    largeCell: 2400,
    cellNums: 10,
    unit: 'second',
  },
  { // 14
    index: 14,
    maxFrame: 1/48,
    minFrame: 1/96,
    largeCell: 4800,
    cellNums: 10,
    unit: 'second',
  },
  { // 15
    index: 15,
    maxFrame: 1/96,
    minFrame: 1/192,
    largeCell: 9600,
    cellNums: 10,
    unit: 'second',
  },
];